version: '3.4'

x-fastapi-envs: &fastapi_envs
  environment:
    - PROJECT_NAME=mcenter
    - NGINX_HOST=api.mcenter.com
    - ENV=prod
    - POSTGRES_USER=mcenter
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_HOST=db
    - POSTGRES_DB=mcenter
    - POSTGRES_PORT=5432
    - VERSION=v1
    - DEBUG=False

x-default_deploy: &default_deploy
  deploy:
    mode: replicated
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 20s
      max_attempts: 6
      window: 120s
    update_config:
      parallelism: 1
      order: start-first

volumes:
  data-vol:
  dbdata-vol:
  nginxdata-vol:

services:
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #   labels:
  #     com.mcenter.container.name: mcenter-db
  #     com.mcenter.env: prod
  #     com.mcenter.project: mcenter-cloud
  #   volumes:
  #     - dbdata-vol:/var/lib/postgresql/data/
  #   <<: [*fastapi_envs, *default_deploy]

  nginx:
    image: ${REGISTRY}/nginx:${GITHUB_SHA}
    environment:
      - UPSTREAMS=/:backend:8000
      - NGINX_SERVER_NAME=api.mcenter.com # without this, /admin redirects to https://_/
      - ENABLE_SSL=true
      - HTTPS_REDIRECT=true
      - CERTBOT_EMAIL=coutinholps@gmail.com
      - DOMAIN_LIST=api.mcenter.com

    labels:
      com.mcenter.container.name: mcenter-nginx
      com.mcenter.env: prod
      com.mcenter.project: mcenter-cloud
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    volumes:
      - nginxdata-vol:/etc/letsencrypt
    <<: *default_deploy

  backend:
    image: ${REGISTRY}/backend:${GITHUB_SHA}
    environment:
    labels:
      com.mcenter.container.name: mcenter-backend
      com.mcenter.env: prod
      com.mcenter.project: mcenter-cloud
    <<: [*fastapi_envs, *default_deploy]
    volumes:
      - data-vol:/data
    command: bash -c "
      alembic upgrade head &&
      gunicorn src.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level=info --timeout=120"
